<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DXPeditions.Core\DXPeditions.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyTitle>DXPeditions Tracker</AssemblyTitle>
    <Product>DXPeditions Tracker</Product>
    <Version>1.1.0</Version>
    <FileVersion>1.1.0.0</FileVersion>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Logo.png" />
    <EmbeddedResource Include="Resources\Logo.png" />
  </ItemGroup>

</Project>